### PR TITLE
openVPN

### PR DESCRIPTION
**Pull request by yuguowen**
Glad to see your demo, I should how to connect to our own openvpn configuration server, do you have such case. Thank you very much!

### CODE REVIEW

**Comment by Duraiamuthan** [comment]
The approach is still the same 👍

**Comment by yuguowen** [comment]
Thank you for your reply, but can you give me a source of openvpn demo?Thank you very much

**Comment by yuguowen** [comment]
@Duraiamuthan Thank you for your reply, but can you give me a source of openvpn demo?Thank you very much

**Comment by Duraiamuthan** [comment]
@yuguowen - You just have to make a mobile config with the values w.r.t your openvpn server.Using iPCU you can easily do that then you have to install that mobile config in your device by mailing yourself or hosting it in a web server and open the mobile config via browser or you can open it from your app using OpenURL. make sure OpenVPN connect is installed in your device.Use the reference document that I have shared for making mobile config.

**Comment by yuguowen** [comment]
@Duraiamuthan Thank you for your answer, can you tell me how to connect to your own openvpn server?It is better to have a source?Thank you.

**Comment by Duraiamuthan** [comment]
I have closed my openvpn server and you can try with free OpenVPN server online

**Comment by Duraiamuthan** [comment]
You can try this as well http://www.vpnbook.com/freevpn

**Comment by yuguowen** [comment]
@Duraiamuthan  Thank you for your reply, may I didn't say understand me, I said we have our own openvpn server, I now do is iOS client. I want to use the code connection openvpn server. Do you have any good demo?

**Comment by Duraiamuthan** [comment]
@yuguowen  Plz follow this tutorial (https://github.com/Duraiamuthan/VPN-iOS/blob/master/OpenVPN.doc) and you can follow this dummy sample on making your mobile config (https://github.com/Duraiamuthan/VPN-iOS/blob/master/Samples/MobileConfig.mobileconfig)

**Comment by yuguowen** [comment]
@Duraiamuthan Thank you again.I'm glad to hear that.But unfortunately I don't understand how to do what you say.Should you explain clearly.Thanks again.

**Comment by yuguowen** [comment]
Do you have openvpn ios version of the source or the third party SDK?

**Comment by yuguowen** [comment]
@Duraiamuthan Do you have openvpn ios version of the source or the third party SDK?

**Comment by Duraiamuthan** [comment]
@yuguowen - Ok,We can't create an app with OpenVPN library because apple won't allow the app to run unless the apple gives entitlement for the app.The entitlement for VPN is held by only some handful of companies across the globe. Whereas in Android this is not the case you can integrate the OpenVPN library with your app and run it.So basically what you can do here is apart from your own app you need to have [OpenVPN application](https://itunes.apple.com/in/app/openvpn-connect/id590379981?mt=8) installed in the device as an auxiliary which is to establish VPN connection from the iOS Device.so in your app you can have the link to mobile config that is hosted on server.if you open the mobile config ,it'll get installed in iOS Device then OpenVPN app will use it make VPN connection for you.If you go through [this](https://github.com/Duraiamuthan/VPN-iOS/blob/master/OpenVPN.doc) you can learn how to create the mobile config.I hope I have made it clear.Please don't hesitate to get any clarification.

**Pull request closed without merging**
